### ISSUE TITLE
AdobeReaderURLProvider error, not finding Adobe Reader download URL

### ISSUE THREAD

**Issue by smashism** [autopkg/recipes#229]
`Processor: AdobeReaderURLProvider: Error: Can't find Adobe Reader download URL for English, version AcrobatDC
`
I did a more verbose run but got the same output on the error. Maybe Adobe changed the URL? I'm not entirely sure where folks find that information from Adobe. I referenced homebrew's cask but they just manually pass a version number through a URL and the AdobeReaderURLProvider seems to behave a bit differently. Happy to dig deeper if needed, I just wanted to report it since I asked around on Slack and other folks are getting the same error.

**Comment by rickheil** [comment]
The get.adobe.com link in AdobeReaderURLProvider.py is now 302 redirecting to adobe.com. Perhaps the JSON feed was retired?

**Comment by rickheil** [comment]
I did some more playing around and found my issue was that my override was passing OS_VERSION as 10.9 - ReaderDC is 10.10+ so it wasn't finding a URL for it obviously.

**Comment by smashism** [comment]
Confirming that overriding the OS_Version to 10.10 worked for me as well.

**Comment by deesweet** [comment]
^Would like to confirm the above as well - overriding OS_Version to 10.10 appears to resolve the issue.

**Comment by mtconleyuk** [comment]
Yes, that seems to have worked. FWIW, I overrode the OS_VERSION and set the minimum_os_version to 10.10.0.

**Comment by loopway** [comment]
Still had to create an override for the munki receipt. More updates needed?

**Comment by krispayne** [comment]
I updated my override to 10.11.0 and I was able to download 19.008.20071, however, aren't there later versions? I tried updating the override to 10.12.0, but saw no change.

**Comment by gregneagle** [comment]
"aren't there later versions?"  I don't know -- I think that would be the reporter's responsibility to determine if he/she thinks the recipe isn't getting the correct current version. If you know of some, it would be helpful to point to links, or better, the XML feeds that point to them.

**Comment by krispayne** [comment]
My JSS is reporting later versions in patch management, but that hasn't always been a reliable source of truth.

If I go to the adobe download site, though, 19.008.200071 is the version that gets downloaded. 

I guess this wasn't the right place to ask that question. Sorry for the trouble, was just trying to find out if this was broken again.

**Comment by krispayne** [comment]
Updated my OS version in the recipe to 10.13.0 and removed OS requirements below that version and the recipe is downloading recent versions again.

Looks like PR's 271, 297, 298, and 299 address this, do we know what is blocking the merge?

**Comment by gregneagle** [comment]
I still think the correct solution here is to update the .download recipe (which was done) and then _remove_ OS_VERSION from the child recipes. This way in the future, updates can be made one place.

As for what people running these recipes can/should do is define OS_VERSION in their override.

**Comment by krispayne** [comment]
@gregneagle good point. I’ll look that recipe up and check for PR’s

**Comment by homebysix** [comment]
For me, the recipe still works with `OS_VERSION` as `10.12.0`, and downloads a package named AcroRdrDC_2001320074_MUI.dmg.

Setting `OS_VERSION` to `10.14.0` downloads a package named AcroRdrDC_2100120140_MUI.dmg.

There's a reasonable case to be made for AutoPkg input variables supplying the "latest" version by default and allowing administrators to override whenever they want older versions. However I don't think that change is urgent for the AdobeReaderDC recipes given the `10.12.0` default still works.

Verbose run output below:

```
% autopkg run -vvq -k OS_VERSION=10.12.0 'AdobeReader/AdobeReaderDC.download.recipe'
Processing AdobeReader/AdobeReaderDC.download.recipe...
WARNING: AdobeReader/AdobeReaderDC.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
AdobeReaderURLProvider
{'Input': {'language': 'English',
           'major_version': 'AcrobatDC',
           'os_version': '10.12.0'}}
AdobeReaderURLProvider: Found URL http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2001320074/AcroRdrDC_2001320074_MUI.dmg
{'Output': {'url': 'http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2001320074/AcroRdrDC_2001320074_MUI.dmg'}}
URLDownloader
{'Input': {'filename': 'AdobeReaderDC.dmg',
           'url': 'http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2001320074/AcroRdrDC_2001320074_MUI.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing ~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg
{'Output': {'pathname': '~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'expected_authority_names': ['Developer ID Installer: Adobe '
                                        'Systems, Inc. (JQ525L2MZD)',
                                        'Developer ID Certification Authority',
                                        'Apple Root CA'],
           'input_path': '~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg/*.pkg'}}
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg
CodeSignatureVerifier: Using path '/private/tmp/dmg.CuLeox/AcroRdrDC_2100120140_MUI.pkg' matched from globbed '/private/tmp/dmg.CuLeox/*.pkg'.
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "AcroRdrDC_2100120140_MUI.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2021-02-19 21:13:54 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Adobe Systems, Inc. (JQ525L2MZD)
CodeSignatureVerifier:        Expires: 2022-02-07 21:51:11 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            45 02 B6 EB AA C8 56 12 A8 82 5D 34 C0 7C 86 FB 8C 16 AF 0F 47 55
CodeSignatureVerifier:            05 C6 98 A8 02 1A F6 7D 5C 95
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
{'Output': {}}
Receipt written to ~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/receipts/AdobeReaderDC.download-receipt-20210225-111343.plist

Nothing downloaded, packaged or imported.
```

```
% autopkg run -vvq -k OS_VERSION=10.14.0 'AdobeReader/AdobeReaderDC.download.recipe'
Processing AdobeReader/AdobeReaderDC.download.recipe...
WARNING: AdobeReader/AdobeReaderDC.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
AdobeReaderURLProvider
{'Input': {'language': 'English',
           'major_version': 'AcrobatDC',
           'os_version': '10.14.0'}}
AdobeReaderURLProvider: Found URL http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2100120140/AcroRdrDC_2100120140_MUI.dmg
{'Output': {'url': 'http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2100120140/AcroRdrDC_2100120140_MUI.dmg'}}
URLDownloader
{'Input': {'filename': 'AdobeReaderDC.dmg',
           'url': 'http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2100120140/AcroRdrDC_2100120140_MUI.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing ~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg
{'Output': {'pathname': '~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'expected_authority_names': ['Developer ID Installer: Adobe '
                                        'Systems, Inc. (JQ525L2MZD)',
                                        'Developer ID Certification Authority',
                                        'Apple Root CA'],
           'input_path': '~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg/*.pkg'}}
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/downloads/AdobeReaderDC.dmg
CodeSignatureVerifier: Using path '/private/tmp/dmg.LgUmoQ/AcroRdrDC_2100120140_MUI.pkg' matched from globbed '/private/tmp/dmg.LgUmoQ/*.pkg'.
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "AcroRdrDC_2100120140_MUI.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2021-02-19 21:13:54 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Adobe Systems, Inc. (JQ525L2MZD)
CodeSignatureVerifier:        Expires: 2022-02-07 21:51:11 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            45 02 B6 EB AA C8 56 12 A8 82 5D 34 C0 7C 86 FB 8C 16 AF 0F 47 55
CodeSignatureVerifier:            05 C6 98 A8 02 1A F6 7D 5C 95
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
{'Output': {}}
Receipt written to ~/Library/AutoPkg/Cache/com.github.autopkg.download.AdobeReaderDC/receipts/AdobeReaderDC.download-receipt-20210225-111353.plist

Nothing downloaded, packaged or imported.
```

**Comment by opus-nbo** [comment]
I think my recent problem with this recipe is related to this ticket:

```
AdobeReaderURLProvider
{'Input': {'language': 'English',
           'major_version': 'AcrobatDC',
           'os_version': '10.15.0'}}
AdobeReaderURLProvider: Curl command: ['/usr/bin/curl', '--compressed', '--location', '--header', 'x-requested-with: XMLHttpRequest', 'http://get.adobe.com/reader/webservices/json/standalone/?platform_type=Macintosh&platform_dist=OSX&platform_arch=x86-32&platform_misc=10.15.0&language=English&eventname=readerotherversions']
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/AdobeReader/AdobeReaderURLProvider.py", line 101, in main
    base_url, language, major_version, os_version
  File "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/AdobeReader/AdobeReaderURLProvider.py", line 77, in get_reader_dmg_info
    reader_info = json.loads(json_response)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Expecting value: line 1 column 1 (char 0)
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.AdobeReaderDC/receipts/local.munki-receipt-20220502-103255.plist

The following recipes failed:
    local.munki.AdobeReaderDC
        Error in local.munki.AdobeReaderDC: Processor: AdobeReaderURLProvider: Error: Expecting value: line 1 column 1 (char 0)
```
