### ISSUE TITLE
com.github.autopkg.download.googlechrome CodeSignature problem

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/recipes#422]
Using AutoPkg 2.4.1 (and previous version), I get an error regarding the CodeSignatureVerifier at https://github.com/autopkg/recipes/blob/master/GoogleChrome/GoogleChrome.download.recipe

Recached the recipe beforehand, no change.

AutoPkg verbose output `-vvvv`

```
CodeSignatureVerifier
{'Input': {'input_path': '/Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg/Google '
                         'Chrome.app',
           'requirement': '(identifier "com.google.Chrome" or identifier '
                          '"com.google.Chrome.beta" or identifier '
                          '"com.google.Chrome.dev" or identifier '
                          '"com.google.Chrome.canary") and (certificate leaf = '
                          'H"85cee8254216185620ddc8851c7a9fc4dfe120ef" or '
                          'certificate leaf = '
                          'H"c9a99324ca3fcb23dbcc36bd5fd4f9753305130a")',
           'strict_verification': False}}
CodeSignatureVerifier: Mounted disk image /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification disabled...
CodeSignatureVerifier: /private/tmp/dmg.fLHgX7/Google Chrome.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.fLHgX7/Google Chrome.app: satisfies its Designated Requirement
CodeSignatureVerifier: test-requirement: code failed to satisfy specified code requirement(s)
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/CodeSignatureVerifier.py", line 351, in main
    self.process_code_signature(matched_input_path)
  File "/Library/AutoPkg/autopkglib/CodeSignatureVerifier.py", line 240, in process_code_signature
    "Code signature verification failed. Note that "
autopkglib.ProcessorError: Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
```

**Comment by opus-nbo** [comment]
Please merge this https://github.com/autopkg/recipes/pull/421/files/67a332b180164a66d20ad99835c55e4113cefb52

**Comment by homebysix** [comment]
Resolved by https://github.com/autopkg/recipes/pull/421. Thank you!
